### ISSUE TITLE
C source does not match V source

### ISSUE THREAD

**Issue by vitalyster** [vlang/vc#4]
for example, `v.c` still have unconditional `#include <dirent.h>` while V sources have it in `os_nix.v`

**Comment by spytheman** [comment]
The C source does match the V source more or less (well, I guess that v.c is produced by running the generated C file through a beautifier like clang-format).

You can try:
```
./v -o c_source_of_v_compiler.c compiler
colordiff -w v.c c_source_of_v_compiler.c
```

=> It is mostly the same, except that some includes are reordered, and some long lines are broken to  several ones.

**Comment by vitalyster** [comment]
Great, now I did not see platform specific includes
